/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardVideosRouteImport } from './routes/dashboard/videos'
import { Route as DashboardUploadRouteImport } from './routes/dashboard/upload'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashboardQuickRouteImport } from './routes/dashboard/quick'
import { Route as DashboardAdvancedRouteImport } from './routes/dashboard/advanced'
import { Route as DashboardResultVideoIdRouteImport } from './routes/dashboard/result.$videoId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardVideosRoute = DashboardVideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardUploadRoute = DashboardUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardQuickRoute = DashboardQuickRouteImport.update({
  id: '/quick',
  path: '/quick',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdvancedRoute = DashboardAdvancedRouteImport.update({
  id: '/advanced',
  path: '/advanced',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardResultVideoIdRoute = DashboardResultVideoIdRouteImport.update({
  id: '/result/$videoId',
  path: '/result/$videoId',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard/advanced': typeof DashboardAdvancedRoute
  '/dashboard/quick': typeof DashboardQuickRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/upload': typeof DashboardUploadRoute
  '/dashboard/videos': typeof DashboardVideosRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/result/$videoId': typeof DashboardResultVideoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard/advanced': typeof DashboardAdvancedRoute
  '/dashboard/quick': typeof DashboardQuickRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/upload': typeof DashboardUploadRoute
  '/dashboard/videos': typeof DashboardVideosRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/result/$videoId': typeof DashboardResultVideoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard/advanced': typeof DashboardAdvancedRoute
  '/dashboard/quick': typeof DashboardQuickRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/upload': typeof DashboardUploadRoute
  '/dashboard/videos': typeof DashboardVideosRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/result/$videoId': typeof DashboardResultVideoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/signup'
    | '/dashboard/advanced'
    | '/dashboard/quick'
    | '/dashboard/settings'
    | '/dashboard/upload'
    | '/dashboard/videos'
    | '/dashboard/'
    | '/dashboard/result/$videoId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/dashboard/advanced'
    | '/dashboard/quick'
    | '/dashboard/settings'
    | '/dashboard/upload'
    | '/dashboard/videos'
    | '/dashboard'
    | '/dashboard/result/$videoId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/signup'
    | '/dashboard/advanced'
    | '/dashboard/quick'
    | '/dashboard/settings'
    | '/dashboard/upload'
    | '/dashboard/videos'
    | '/dashboard/'
    | '/dashboard/result/$videoId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/videos': {
      id: '/dashboard/videos'
      path: '/videos'
      fullPath: '/dashboard/videos'
      preLoaderRoute: typeof DashboardVideosRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/upload': {
      id: '/dashboard/upload'
      path: '/upload'
      fullPath: '/dashboard/upload'
      preLoaderRoute: typeof DashboardUploadRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/quick': {
      id: '/dashboard/quick'
      path: '/quick'
      fullPath: '/dashboard/quick'
      preLoaderRoute: typeof DashboardQuickRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/advanced': {
      id: '/dashboard/advanced'
      path: '/advanced'
      fullPath: '/dashboard/advanced'
      preLoaderRoute: typeof DashboardAdvancedRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/result/$videoId': {
      id: '/dashboard/result/$videoId'
      path: '/result/$videoId'
      fullPath: '/dashboard/result/$videoId'
      preLoaderRoute: typeof DashboardResultVideoIdRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardAdvancedRoute: typeof DashboardAdvancedRoute
  DashboardQuickRoute: typeof DashboardQuickRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardUploadRoute: typeof DashboardUploadRoute
  DashboardVideosRoute: typeof DashboardVideosRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardResultVideoIdRoute: typeof DashboardResultVideoIdRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAdvancedRoute: DashboardAdvancedRoute,
  DashboardQuickRoute: DashboardQuickRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardUploadRoute: DashboardUploadRoute,
  DashboardVideosRoute: DashboardVideosRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardResultVideoIdRoute: DashboardResultVideoIdRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
